### ISSUE TITLE
course material roadmap

### ISSUE THREAD

**Issue by gundelbacher** [web4x/codingWeb4#18]
https://github.com/web4x/codingWeb4#readme

git submodules fot the diffrent Training chapters
as @phibar did it for UcpComponents
also use web4chapter tag as ucp-component tag

- [ ] ask phibar how
- [ ] review ONCE.ts examples and okta.js intergrarion
- [ ] learn how to split the chapters into submodules
- [ ] write a small chapter about writing the automation

Split the Chapter [Web 2.0](https://github.com/web4x/codingWeb4#web-20)

- [ ] keep the outline level 1 and 2 on the readme page
- [ ] split out the details int the readme.md of the submodule

**Comment by phibar** [comment]
How can i help you?

**Comment by gundelbacher** [comment]
@phibar  Would you be somewhere available for a session, to show me how you implement the git submodules?

**Comment by gundelbacher** [comment]
putting the topic on-hold. Sub modules can be a hustle and a good automation must be developed
